/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public static void main(String[] args) {
    String saludo = "Hola mundo";
    System.out.println(saludo);
    saludo = "Adios mundo";
    System.out.println(saludo);
  }
}
