/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;

public class App {
  public static void main(String[] args) {
    ArrayList<Integer> listaDePares = new ArrayList<Integer>();
    int numeroInicial = 2;
    int currentIndex = 0;
    listaDePares.add(numeroInicial);
    System.out.println(listaDePares.get(currentIndex));

    for (int i = 1; i <= 10; i++) {
      listaDePares.add(duplicar(listaDePares.get(currentIndex)));
      currentIndex = currentIndex++;
      System.out.println("Curremt index = " + currentIndex);
      System.out.println(listaDePares.get(currentIndex));
    }
  }

  public static int duplicar(int numero) {
    return numero * 2;
  }
}
